### ISSUE TITLE
attempt to calculate the remainder with a divisor of zero

### ISSUE THREAD

**Issue by rx80** [zitsen/xlsx2csv.rs#1]
When trying to convert a file i get:
`thread 'main' panicked at 'attempt to calculate the remainder with a divisor of zero', /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/xlsx2csv-0.1.0/src/main.rs:126:16`
It seems the offending line is:
`if i % (size.0 / 100) == 0 {`
So `size.0` has to be `0` at some point. I'm not good enough with Rust to debug further.

**Comment by zitsen** [comment]
I'll try

**Comment by zitsen** [comment]
Could you tell me the use case that 
> So `size.0` has to be `0` at some point.

I'll just print out an error and do nothing to continue to the next sheet, if you don't mind.

```diff
index c8b0c69..9df90da 100644
--- c/src/main.rs
+++ i/src/main.rs
@@ -119,6 +119,10 @@ fn main() {
         let mut wtr = csv::WriterBuilder::new().delimiter(*delimiter).from_path(path).expect("open csv");
         let size = range.get_size();
         println!("** sheet range size is {:?}", size);
+        if size.0 == 0 || size.1 == 0 {
+            eprintln!("worsheet range sizes should not be 0, continue");
+            continue;
+        }
         println!("** start writing", );
         let mut pb = ProgressBar::new(100);
         let rows = range.rows();

```

**Comment by rx80** [comment]
@zitsen I think i explained it badly. It's a valid xlsx file, but it produces an error. Can i send you the example file to your email, or i can upload it somewhere?

**Comment by zitsen** [comment]
@rx80 email me please
