### ISSUE TITLE
Request: Windows binaries

### ISSUE THREAD

**Issue by gd4c** [zitsen/xlsx2csv.rs#10]
Is it possible for you to release Windows builds? Thanks

**Comment by zitsen** [comment]
I've created github workflows for windows builds, here is a test binary, you can try: https://github.com/zitsen/xlsx2csv.rs/releases/download/release-test/xlsx2csv.exe

**Comment by zitsen** [comment]
After then, binaries will be released by github actions for each release.

**Comment by gd4c** [comment]
Brilliant! Thanks a lot!

**Comment by zitsen** [comment]
appreciate that you find it helpful, :smile:
