### ISSUE TITLE
Panick with ods file

### ISSUE THREAD

**Issue by ngirard** [zitsen/xlsx2csv.rs#11]
Using the precompiled binary on Ubuntu 20.04.
doing
```sh
xlsx2csv test.ods
```
results in
```
thread 'main' panicked at 'open xlsx file: PackageContentTypeError', src/main.rs:206:69
```
The same document, when converted to xslx, can be converted flawlessly.

The `test.ods` file can be found in the attached `test.zip`

[test.zip](https://github.com/zitsen/xlsx2csv.rs/files/6176466/test.zip)

**Comment by zitsen** [comment]
.ods file support has been broken since v0.4.0, I'll check it soon.

**Comment by zitsen** [comment]
Currently , you could use https://github.com/zitsen/xlsx2csv.rs/releases/download/release-test/xlsx2csv_amd64 for .ods file

**Comment by ngirard** [comment]
Thanks for your feedback!
Indeed, the binary you mentioned works just fine.
BTW, why the switch from calamine to your own parser, if you don't mind me asking ?

**Comment by zitsen** [comment]
`calamine` xlsx parser does not support datetime cell type and custom formated string, it just puts out the timestamp for a time format like `2021-03-12 12:00:00`.

**Comment by ngirard** [comment]
I see, thanks !
