### ISSUE TITLE
Usage and Installation under Windows

### ISSUE THREAD

**Issue by larry77** [zitsen/xlsx2csv.rs#13]
Hello,
A question really and not a bug report.
I have been using this software for a while on my linux platform and it is brilliant!
I know next to nothing about rust and cargo, but my question is if xlsx2csv would work also on a windows platform so that I can recommend it to other users.
Many thanks.

**Comment by zitsen** [comment]
It is sure that should work on windows. I've published linux/mac/win64 binaries in github release page. Please check <https://github.com/zitsen/xlsx2csv.rs/releases/tag/v0.4.2>.
