### ISSUE TITLE
Add support for  xls, xlsm, xlsb, xla, xlam and ods spreadsheet inputs

### ISSUE THREAD

**Issue by virtualritz** [zitsen/xlsx2csv.rs#3]
Since [calamine](https://github.com/tafia/calamine) supports all these formats, xlsx2csv.rs could be extended to do so too.
Then the name should probably be changed to sheet2csv. :)

**Comment by virtualritz** [comment]
Calamine ships an [example](https://github.com/tafia/calamine/blob/master/examples/excel_to_csv.rs) for this, btw.

**Comment by zitsen** [comment]
Sorry for the late response, I'll figure it out.
