### ISSUE TITLE
Convert datetimes

### ISSUE THREAD

**Issue by alexwennerberg** [zitsen/xlsx2csv.rs#6]
Right now, the program does not properly handle datetime objects. I think ideally it should convert these to a datetime string.

**Comment by dpriskorn** [comment]
Could you give an example?

**Comment by alexwennerberg** [comment]
@egils-consulting Sorry, this was nearly a year ago and I do not remember the issue I was having

**Comment by zitsen** [comment]
Datetime with format in .xlsx is supported since v0.4.0 , closed
