### ISSUE TITLE
Argument syntax leads to unpredictable output

### ISSUE THREAD

**Issue by dpriskorn** [zitsen/xlsx2csv.rs#8]
Hi
I really like this tool, its way faster than ssconvert from gnumeric but it has a big drawback I think should be fixed.

When invoking there does not seem to be a way to specify the output file. Thats a bug.

I suggest changing to follow the syntax of ssconvert.
xlsx2csv input.xlsx output.csv
WDYT?

**Comment by zitsen** [comment]
Because .xlsx files have multitple worksheets.

A option is:

program <excel> <sheetsoutput...>

Like:

xlsx2csv work.xlsx sheet1.csv sheet2.csv

Is this better?

**Comment by dpriskorn** [comment]
Yeah I know. How about a switch argument --all to save multiple and default to only work on the first one?
The most simple case is the most common I think.

**Comment by zitsen** [comment]
@egils-consulting New command line options syntax updated, check for your usecase.
